#!/bin/bash

# 设置配置路径
CONFIG_PATH="./config.json"

# 启动 sing-box 后台运行
nohup sing-box run -c "$CONFIG_PATH" > /tmp/sing-box.log 2>&1 &
echo $! > /tmp/sing-box.pid

# 设置 GNOME 系统代理
gsettings set org.gnome.system.proxy mode 'manual'

gsettings set org.gnome.system.proxy.socks host '127.0.0.1'
gsettings set org.gnome.system.proxy.socks port 1080 
